name: nmeeting
description: vn.vnpthcm.nmeeting

# Flutter SDK: 3.27.4

# https://appstore.hcmtelecom.vn/ttcntt/.html
# Name: CSDL Tổng hợp - VRG
# Android: vn.vnpthcm.nmeeting
# IOS: vn.vnpthcm.nmeeting
# https://console.firebase.google.com/u/4/project/
# https://console.cloud.google.com/

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
#  flutter_windowmanager:
#    git:
#      url: https://github.com/ndthien2911/flutter_windowmanager.git
#      ref: master
  qr_code_scanner:
    git:
      url: https://github.com/ndthien2911/qr_code_scanner.git
      ref: master

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  rxdart: ^0.27.2
  pin_code_fields: ^7.4.0
  table_calendar: ^3.0.3
  intl: ^0.19.0
  # qr_flutter: ^3.1.0
  # qr_code_scanner: ^0.6.1
  image_picker: ^1.0.4
  oktoast: ^3.4.0
  device_info_plus: ^11.3.0
  shared_preferences: ^2.0.8
  # progress_dialog: ^1.2.4
  connectivity_plus: ^6.1.4
  web_socket_channel: ^2.1.0
  permission_handler: ^10.0.2
  path_provider: ^2.0.6
#  flutter_datetime_picker: ^1.3.8
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.1.5
  keyboard_actions: ^4.2.0
  # webview_flutter: ^1.0.7
  package_info_plus: ^8.3.0
  timezone: ^0.9.0
  # scrolling_years_calendar: ^1.3.1
  flutter_cached_pdfview: ^0.4.0-nullsafety
  firebase_messaging: ^15.2.2
  firebase_core_platform_interface: 5.4.0
  flutter_local_notifications: ^17.0.0
  # dropdown_formfield: ^0.1.3
  # datetime_picker_formfield: ^1.0.0
  # file_picker: ^4.2.1
  # provider: ^4.3.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  # flutter_pdfview: ^1.2.1
  flutter_inappwebview: ^6.1.2
  # webview_flutter: ^2.3.0
  # qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.1.1
  geolocator: ^13.0.3
  font_awesome_flutter: ^9.2.0
  flutter_native_splash: ^2.3.6
  # flutter_windowmanager: ^0.2.0
  maps_toolkit: ^2.0.0
  device_preview: ^1.1.0
  sizer: ^2.0.15
  jovial_svg: ^1.1.19
  dio: ^5.4.0
  easy_localization: ^3.0.7+1
  carousel_slider: ^5.0.0
  dots_indicator: ^2.1.1
  jwt_decode: ^0.3.1
  local_auth: ^2.1.7
  spreadsheet_decoder: ^2.3.0
  flutter_slidable: ^4.0.0
  progress_dialog_null_safe: ^3.0.0
  add_2_calendar: ^2.1.2
  webview_flutter: ^4.13.0
  flutter_polygon: ^0.3.0+2
  speech_to_text: ^6.5.0
  dotted_border: ^2.1.0
  flutter_datetime_picker_plus: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  # https://appstore.hcmtelecom.vn/ttcntt/csdltonghopvrg.html
  image_path_android: "lib/assets/icons/android-app-icon.png"
  image_path_ios: "lib/assets/icons/ios-app-icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
#  fonts:
#    - family: PlusJakartaSans
#      fonts:
#        - asset: lib/assets/fonts/PlusJakartaSans/PlusJakartaSans-Regular.ttf
#          weight: 400
#        - asset: lib/assets/fonts/PlusJakartaSans/PlusJakartaSans-Medium.ttf
#          weight: 500
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: lib/assets/fonts/Roboto-Regular.ttf
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  generate: true
  uses-material-design: true
  assets:
    - lib/assets/images/
#    - lib/assets/images/no-avatar.png
#    - lib/assets/images/main-logo.png
#    - lib/assets/images/login-logo.png
#    - lib/assets/images/qrcode-bg.jpg
#    - lib/assets/images/scan-me.png
#    - lib/assets/images/right-bg.png
#    - lib/assets/images/splash.png
#    - lib/assets/images/change-password-banner.png
#    -  lib/assets/images/appBarHome.png

    # icons
    - lib/assets/icons/
#    - lib/assets/icons/setting-profile.png
#    - lib/assets/icons/setting-info.png
#    - lib/assets/icons/setting-vnface.png
#    - lib/assets/icons/setting-logout.png
#    - lib/assets/icons/setting-changepass.png
#    - lib/assets/icons/mini-places.svg
#    - lib/assets/icons/ic-map-meeting-not-start.svg
#    - lib/assets/icons/ic-map-meeting-in-progress.svg
#    - lib/assets/icons/ic-map-meeting-finished.svg
#    - lib/assets/icons/prefix-username.svg
#    - lib/assets/icons/prefix-password.svg
#    - lib/assets/icons/ic-report.svg
#    - lib/assets/icons/quiz.png
#    - lib/assets/icons/ic-back-main-color.svg
#    - lib/assets/icons/ic-back-white-color.svg
#    - lib/assets/icons/line.svg
#    - lib/assets/icons/ic-show-password.svg
#    - lib/assets/icons/ic-hide-password.svg
#    - lib/assets/icons/home-name.svg
#    - lib/assets/icons/home-seat.svg
#    - lib/assets/icons/home-checkin.svg
#    - lib/assets/icons/home-time.svg
#    - lib/assets/icons/home-address.svg
#    - lib/assets/icons/home-car-number.svg
#    - lib/assets/icons/home-room-number.svg
#    - lib/assets/icons/icon-bellHome.svg
#    - lib/assets/icons/icon-settingHome.svg
#    - lib/assets/icons/arrow-left.png
#    - lib/assets/icons/login-username-prefix.svg
#    - lib/assets/icons/login-password-prefix.svg
#    - lib/assets/icons/ic-back-black-color.svg
    # To add assets to your application, add an assets section, like this:


  # - asset: fonts/Roboto.ttf
  #   style: italic

  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# flutter pub run flutter_native_splash:create
flutter_native_splash:

  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "#ffffff"
  # background_image: "assets/background.png"

  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing 
  # the leading # character.

  # The image parameter allows you to specify an image used in the splash screen.  It must be a 
  # png file and should be sized for 4x pixel density.
  # https://appstore.hcmtelecom.vn/ttcntt/csdltonghopvrg.html
  image: lib/assets/images/splash.png

  # The color_dark, background_image_dark, and image_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or 
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.
  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png

  # The android, ios and web parameters can be used to disable generating a splash screen on a given 
  # platform.
  #android: false
  #ios: false
  #web: false

  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see 
  # https://developer.android.com/reference/android/view/Gravity): bottom, center, 
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see 
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill, 
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight, 
  # bottomLeft, or bottomRight.
  #ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center

  # To hide the notification bar, use the fullscreen parameter.  Has no affect in web since web 
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  #fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s) 
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'
